{{- if not .Values.secrets.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "testimony.secretName" . }}
  labels:
    {{- include "testimony.labels" . | nindent 4 }}
type: Opaque
stringData:
  s3-access-key-id: {{ .Values.secrets.s3AccessKeyId | quote }}
  s3-secret-access-key: {{ .Values.secrets.s3SecretAccessKey | quote }}
  auth-api-key: {{ .Values.secrets.authAPIKey | quote }}
{{- end }}
